import { Truck, Package, Thermometer, Zap, Shield, RefreshCw } from 'lucide-react'

// Centralized configuration for truck fleet sizes
// This allows updating sizes, specifications, and descriptions in a single place.

export const truckSizes = [
  {
    id: '14ft',
    size: 14,
    name: '14 Feet Truck',
    label: '14 ft',
    capacity: '2.5 - 3.5 Tons',
    dimensions: '14 x 6 x 6.5 ft',
    volume: '540 cu.ft',
    bestFor: ['Intra-city deliveries', 'E-commerce logistics', 'FMCG distribution', 'Household goods shifting'],
    models: ['Tata Ultra T.7', 'Eicher Pro 2049', 'Mahindra Furio 7'],
    badge: 'City Transport',
    color: 'from-orange-500 to-amber-500',
    accentColor: '#f97316',
    description: 'Perfect for city logistics and navigating tighter roads. Offers high maneuverability with decent cargo space.'
  },
  {
    id: '17ft',
    size: 17,
    name: '17 Feet Truck',
    label: '17 ft',
    capacity: '4.5 - 5.5 Tons',
    dimensions: '17 x 7 x 7 ft',
    volume: '830 cu.ft',
    bestFor: ['Inter-city parcel services', 'Medium machinery', 'Light industrial goods', 'Agricultural produce'],
    models: ['Eicher Pro 2059', 'Tata Ultra 912', 'Ashok Leyland Partner'],
    badge: 'Regional Carrier',
    color: 'from-blue-500 to-indigo-500',
    accentColor: '#3b82f6',
    description: 'Highly versatile regional transport truck. Ideal for medium-weight cargo across neighboring districts.'
  },
  {
    id: '20ft',
    size: 20,
    name: '20 Feet Truck',
    label: '20 ft',
    capacity: '6.5 - 7.5 Tons',
    dimensions: '20 x 7.5 x 7.5 ft',
    volume: '1120 cu.ft',
    bestFor: ['Industrial raw materials', 'Heavy furniture shipments', 'Warehouse relocations', 'Automotive parts'],
    models: ['Tata LPT 1512', 'Eicher Pro 3019', 'Mahindra Furio 14'],
    badge: 'Inter-State Logistics',
    color: 'from-purple-500 to-violet-500',
    accentColor: '#8b5cf6',
    description: 'Bridges the gap between medium and heavy duty. Offers substantial volume capacity for bulk logistics.'
  },
  {
    id: '22ft',
    size: 22,
    name: '22 Feet Truck',
    label: '22 ft',
    capacity: '9.0 - 11.0 Tons',
    dimensions: '22 x 7.8 x 8 ft',
    volume: '1370 cu.ft',
    bestFor: ['Heavy manufacturing components', 'Metal pipes & rods', 'Bulk retail cargo', 'Pharmaceutical batches'],
    models: ['Ashok Leyland Boss 1920', 'Tata Ultra T.16', 'Eicher Pro 6025'],
    badge: 'High Payload',
    color: 'from-emerald-500 to-teal-500',
    accentColor: '#10b981',
    description: 'Designed for heavy-weight transportation. Features robust suspension and high cargo deck height.'
  },
  {
    id: '24ft',
    size: 24,
    name: '24 Feet Truck',
    label: '24 ft',
    capacity: '12.0 - 15.0 Tons',
    dimensions: '24 x 8 x 8.5 ft',
    volume: '1630 cu.ft',
    bestFor: ['Heavy machinery transport', 'Containerized cargo', 'Chemical drums & barrels', 'National distribution'],
    models: ['Tata LPT 1918', 'Ashok Leyland 1920', 'Eicher Pro 6028'],
    badge: 'Super Hauler',
    color: 'from-rose-500 to-red-500',
    accentColor: '#f43f5e',
    description: 'Our largest standard fleet size. Provides maximum volume and load capability for long-haul national transport.'
  }
];

export const services = [
  {
    id: 'ftl',
    icon: Truck,
    title: 'Full Truck Load (FTL)',
    tagline: 'Your cargo, your truck, your timeline.',
    color: '#f97316',
    bg: '#fff8f3',
    border: '#fed7aa',
    badge: 'Most Popular',
    desc: 'Book an entire truck exclusively for your shipment. Ideal for large consignments requiring direct, non-stop delivery without any intermediate handling or delays.',
    features: [
      `${truckSizes.map(t => t.label).join(', ').replace(/, ([^,]*)$/, ' & $1')} options`,
      'Direct pickup to delivery',
      'Dedicated driver assigned',
      'Real-time GPS tracking',
      'Secure sealed containers',
      'Pan India coverage'
    ],
    ideal: 'Manufacturing, wholesale distributors, FMCG, auto parts, e-commerce',
    transit: '1–5 days depending on distance',
  },
  {
    id: 'ltl',
    icon: Package,
    title: 'Part Load (LTL)',
    tagline: 'Pay only for what you ship.',
    color: '#3b82f6',
    bg: '#eff6ff',
    border: '#bfdbfe',
    badge: 'Cost-Effective',
    desc: 'Ship smaller loads at full-truck prices without paying for empty space. We consolidate multiple consignments heading the same route to save you money.',
    features: ['Minimum 100 kg', 'Hub-to-hub network', 'Competitive per-kg rates', 'Daily departures', 'Secure consolidation centres', 'Digital weight tracking'],
    ideal: 'SMEs, startups, retail distributors, seasonal shippers',
    transit: '2–7 days',
  },
  {
    id: 'cold',
    icon: Thermometer,
    title: 'Cold Chain Logistics',
    tagline: 'Temperature-perfect, every time.',
    color: '#06b6d4',
    bg: '#ecfeff',
    border: '#a5f3fc',
    badge: 'Specialized',
    desc: 'Fully refrigerated and temperature-controlled fleet for products that can\'t afford temperature deviations. From 2°C to 25°C — we maintain your spec throughout the journey.',
    features: ['Multi-temperature zones', 'IoT temperature loggers', 'Compliance documentation', 'Pharma-grade vehicles', 'Cold storage network', 'FSSAI compliant'],
    ideal: 'Pharmaceuticals, food & beverages, dairy, frozen goods, floriculture',
    transit: '1–4 days',
  },
  {
    id: 'express',
    icon: Zap,
    title: 'Express Delivery',
    tagline: '24–48 hours. No compromises.',
    color: '#f59e0b',
    bg: '#fffbeb',
    border: '#fde68a',
    badge: 'Fastest',
    desc: 'Priority freight services for time-critical shipments. Our express network operates around the clock with dedicated priority lanes between major cities.',
    features: ['24-hour metro delivery', '48-hour Tier-2 cities', 'Priority loading', 'Night movement enabled', 'Hourly tracking updates', 'Escalation support'],
    ideal: 'Urgent industrial parts, medical supplies, event materials, perishables',
    transit: '24–48 hours',
  },
  {
    id: 'insured',
    icon: Shield,
    title: 'Insured Transport',
    tagline: 'Complete peace of mind, guaranteed.',
    color: '#10b981',
    bg: '#f0fdf4',
    border: '#a7f3d0',
    badge: 'Guaranteed',
    desc: 'Every consignment is fully insured against transit damage, theft, and loss. Our comprehensive cargo insurance gives you complete financial protection from pickup to delivery.',
    features: ['100% cargo value coverage', 'Instant claim processing', 'No excess on small claims', 'Digital e-POD evidence', 'IRDA-registered insurer', 'Transparent settlement'],
    ideal: 'Electronics, high-value goods, art, antiques, expensive machinery',
    transit: 'Standard / Express options',
  },
  {
    id: 'reverse',
    icon: RefreshCw,
    title: 'Reverse Logistics',
    tagline: 'Smooth returns, stronger supply chains.',
    color: '#8b5cf6',
    bg: '#faf5ff',
    border: '#ddd6fe',
    badge: 'E-commerce',
    desc: 'End-to-end reverse logistics for e-commerce returns, product recalls, refurbishment pickups, and empty packaging retrieval. Streamlined processes that reduce costs.',
    features: ['E-commerce integration API', 'QC at pickup point', 'Secure return warehousing', 'Refurbishment coordination', 'Waste disposal compliance', 'Detailed reporting'],
    ideal: 'E-commerce, consumer electronics, retail chains, FMCG',
    transit: '2–5 days return cycle',
  },
];

export const getTruckBySize = (sizeVal) => {
  const sizeNum = parseInt(sizeVal, 10);
  return truckSizes.find(t => t.size === sizeNum) || null;
};
